### GLOBAL CONFIGURATION VARIABLES ###

DATABASE_HOST="IP/HOST"
DATABSE_USER="USERNAME"
DATABASE_PASSWORD="PASS"
DATABASE_NAME="dhcp_clients"

DATABASE_CONFIG = {
  'user': DATABSE_USER,
  'password': DATABASE_PASSWORD,
  'host': DATABASE_HOST,
  'database': DATABASE_NAME
}

